import { WinningTeam } from "./types";

export function getTeamsForPokemon(pokemonId: number): WinningTeam[] {
  return WINNING_TEAMS.filter(t => t.pokemon.some(m => m.pokemonId === pokemonId));
}

export const WINNING_TEAMS: WinningTeam[] = [
  // ═══ Real Champions Tournament Teams from Pikalytics (June 2026) ═══
  // Source: Limitless VGC, Twitter/X, VGCPastes
  {
    id: "t1",
    name: "Floette Goodstuffs",
    player: "Magnetman",
    placement: "1st Place",
    event: "Champions Online #1 (Limitless)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 983, name: "Kingambit" },
    ],
    archetype: "Standard",
  },
  {
    id: "t2",
    name: "Rain Archaludon",
    player: "413X",
    placement: "1st Place",
    event: "Champions Online #2 (Limitless)",
    pokemon: [
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
    ],
    archetype: "Rain",
  },
  {
    id: "t3",
    name: "Sun Offense",
    player: "nckster",
    placement: "Top 4",
    event: "Champions Online #1 (Limitless)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 3, name: "Venusaur" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 350, name: "Milotic" },
    ],
    archetype: "Sun",
  },
  {
    id: "t4",
    name: "Perish Trap",
    player: "Striider",
    placement: "Top 4",
    event: "Champions Online #1 (Limitless)",
    pokemon: [
      { pokemonId: 94, name: "Gengar", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 983, name: "Kingambit" },
    ],
    archetype: "Perish Trap",
  },
  {
    id: "t5",
    name: "Sand Rush",
    player: "DanSpunta",
    placement: "Top 4",
    event: "Champions Online #2 (Limitless)",
    pokemon: [
      { pokemonId: 248, name: "Tyranitar", isMega: true },
      { pokemonId: 530, name: "Excadrill" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 903, name: "Sneasler" },
    ],
    archetype: "Sand",
  },
  {
    id: "t6",
    name: "Tailwind Offense",
    player: "pokefey",
    placement: "1st Place",
    event: "Champions Weekly (VGCPastes)",
    pokemon: [
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 981, name: "Farigiraf" },
      { pokemonId: 324, name: "Torkoal" },
      { pokemonId: 903, name: "Sneasler" },
    ],
    archetype: "Tailwind",
  },
  {
    id: "t7",
    name: "Rain + Dragon",
    player: "DragonMasterCody",
    placement: "Top 4",
    event: "Champions Online #3 (Limitless)",
    pokemon: [
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 149, name: "Dragonite" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Rain",
  },
  {
    id: "t8",
    name: "Trick Room Control",
    player: "BIlllmads",
    placement: "1st Place",
    event: "Champions Online #3 (Limitless)",
    pokemon: [
      { pokemonId: 981, name: "Farigiraf" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Trick Room",
  },
  {
    id: "t9",
    name: "Floette Balance",
    player: "Snivy13",
    placement: "Top 4",
    event: "Champions Online #2 (Limitless)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Standard",
  },
  {
    id: "t10",
    name: "Mega Gengar Trap",
    player: "Kotori",
    placement: "Top 8",
    event: "Champions Online #1 (Limitless)",
    pokemon: [
      { pokemonId: 94, name: "Gengar", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 983, name: "Kingambit" },
    ],
    archetype: "Perish Trap",
  },
  {
    id: "t11",
    name: "Sand Balance",
    player: "Desu",
    placement: "Top 8",
    event: "Champions Online #2 (Limitless)",
    pokemon: [
      { pokemonId: 248, name: "Tyranitar" },
      { pokemonId: 530, name: "Excadrill" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 10009, name: "Rotom-Wash" },
    ],
    archetype: "Sand",
  },
  {
    id: "t12",
    name: "Sun + Milotic",
    player: "AnimatedEagle",
    placement: "Top 8",
    event: "Champions Online #1 (Limitless)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 3, name: "Venusaur" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
    ],
    archetype: "Sun",
  },
  {
    id: "t13",
    name: "Corviknight Sand",
    player: "jimmysley28",
    placement: "Top 8",
    event: "Champions Online #3 (Limitless)",
    pokemon: [
      { pokemonId: 248, name: "Tyranitar", isMega: true },
      { pokemonId: 530, name: "Excadrill" },
      { pokemonId: 823, name: "Corviknight" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
    ],
    archetype: "Sand",
  },
  {
    id: "t14",
    name: "Whimsicott HO",
    player: "Werick",
    placement: "Top 4",
    event: "Champions Online #3 (Limitless)",
    pokemon: [
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 94, name: "Gengar", isMega: true },
    ],
    archetype: "Tailwind",
  },
  {
    id: "t15",
    name: "Farigiraf TR Sun",
    player: "sempra",
    placement: "Top 8",
    event: "Champions Online #2 (Limitless)",
    pokemon: [
      { pokemonId: 981, name: "Farigiraf" },
      { pokemonId: 324, name: "Torkoal" },
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
    ],
    archetype: "Sun Trick Room",
  },
  {
    id: "t16",
    name: "Rain HO",
    player: "QuelloScarso",
    placement: "Top 8",
    event: "Champions Online #3 (Limitless)",
    pokemon: [
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 149, name: "Dragonite" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Rain",
  },
  {
    id: "t17",
    name: "Politoed Rain",
    player: "broser",
    placement: "Top 8",
    event: "Champions Online #3 (Limitless)",
    pokemon: [
      { pokemonId: 186, name: "Politoed" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 94, name: "Gengar", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Rain",
  },
  {
    id: "t18",
    name: "Gardevoir Balance",
    player: "Ahaze13",
    placement: "Top 8",
    event: "Champions Online #1 (Limitless)",
    pokemon: [
      { pokemonId: 282, name: "Gardevoir", isMega: true },
      { pokemonId: 6, name: "Charizard" },
      { pokemonId: 3, name: "Venusaur" },
      { pokemonId: 350, name: "Milotic" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Sun",
  },

  // ═══ Champions Ranked Ladder Teams — In-Game Battle Stats (April 12, 2026) ═══
  // Source: Nintendo Switch Champions Ranked Doubles, user-scraped

  // ── Image 1 Teams ──

  {
    id: "t19",
    name: "Starmie HO",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 121, name: "Starmie", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 983, name: "Kingambit" },
    ],
    archetype: "Hyper Offense",
  },
  {
    id: "t20",
    name: "Charizard Y Floette Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 670, name: "Floette" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Sun",
  },
  {
    id: "t21",
    name: "Glimmora Offense",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 970, name: "Glimmora", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 981, name: "Farigiraf" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Hyper Offense",
  },
  {
    id: "t22",
    name: "Dragonite Meganium Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 149, name: "Dragonite", isMega: true },
      { pokemonId: 154, name: "Meganium" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Balance",
  },
  {
    id: "t23",
    name: "Floette Standard",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 530, name: "Excadrill" },
    ],
    archetype: "Standard",
  },
  {
    id: "t24",
    name: "Kangaskhan Standard",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 115, name: "Kangaskhan", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Standard",
  },
  {
    id: "t25",
    name: "Chesnaught Froslass Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 652, name: "Chesnaught", isMega: true },
      { pokemonId: 478, name: "Froslass" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Bulky Offense",
  },
  {
    id: "t26",
    name: "Charizard Y Offense",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Sun",
  },
  {
    id: "t27",
    name: "Floette Incin Core",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Standard",
  },
  {
    id: "t28",
    name: "Floette Aero",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
    ],
    archetype: "Standard",
  },
  {
    id: "t29",
    name: "Froslass Gengar Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 478, name: "Froslass", isMega: true },
      { pokemonId: 94, name: "Gengar" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
    ],
    archetype: "Control",
  },
  {
    id: "t30",
    name: "Charizard Y Balance",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Sun",
  },
  {
    id: "t31",
    name: "Froslass Control",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 478, name: "Froslass", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Control",
  },
  {
    id: "t32",
    name: "Floette Rain",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 903, name: "Sneasler" },
    ],
    archetype: "Rain",
  },
  {
    id: "t33",
    name: "Drampa Pinsir Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 780, name: "Drampa", isMega: true },
      { pokemonId: 127, name: "Pinsir" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 981, name: "Farigiraf" },
    ],
    archetype: "Trick Room",
  },

  // ── Image 2 Teams ──

  {
    id: "t34",
    name: "Dragonite Goodstuffs",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 149, name: "Dragonite", isMega: true },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Rain",
  },
  {
    id: "t35",
    name: "Charizard Y Garchomp",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 983, name: "Kingambit" },
    ],
    archetype: "Sun",
  },
  {
    id: "t36",
    name: "Glimmora Greninja Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 970, name: "Glimmora", isMega: true },
      { pokemonId: 658, name: "Greninja" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Hyper Offense",
  },
  {
    id: "t37",
    name: "Floette Anti-Meta",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 350, name: "Milotic" },
    ],
    archetype: "Standard",
  },
  {
    id: "t38",
    name: "Kangaskhan Pelipper",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 115, name: "Kangaskhan", isMega: true },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Rain",
  },
  {
    id: "t39",
    name: "Charizard Y Kingambit",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Sun",
  },
  {
    id: "t40",
    name: "Froslass Offense",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 478, name: "Froslass", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 983, name: "Kingambit" },
    ],
    archetype: "Control",
  },
  {
    id: "t41",
    name: "Lopunny Pelipper",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 428, name: "Lopunny", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 1018, name: "Archaludon" },
    ],
    archetype: "Rain",
  },
  {
    id: "t42",
    name: "Floette Whimsicott",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 547, name: "Whimsicott" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Tailwind",
  },
  {
    id: "t43",
    name: "Dragonite Rain",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 149, name: "Dragonite", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Rain",
  },
  {
    id: "t44",
    name: "Charizard Y Trick Room",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 981, name: "Farigiraf" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Trick Room",
  },
  {
    id: "t45",
    name: "Charizard Y Kangaskhan Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 115, name: "Kangaskhan" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Sun",
  },
  {
    id: "t46",
    name: "Froslass Scarf Mode",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 478, name: "Froslass", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Control",
  },
  {
    id: "t47",
    name: "Froslass Hazards",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 478, name: "Froslass", isMega: true },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 981, name: "Farigiraf" },
    ],
    archetype: "Control",
  },
  {
    id: "t48",
    name: "Scovillain Tyranitar Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 952, name: "Scovillain", isMega: true },
      { pokemonId: 248, name: "Tyranitar" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1018, name: "Archaludon" },
    ],
    archetype: "Sand",
  },

  // ── Image 3 Teams ──

  {
    id: "t49",
    name: "Golurk Offense",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 623, name: "Golurk", isMega: true },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 983, name: "Kingambit" },
    ],
    archetype: "Trick Room",
  },
  {
    id: "t50",
    name: "Hawlucha HO",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 701, name: "Hawlucha", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Hyper Offense",
  },
  {
    id: "t51",
    name: "Aerodactyl Floette Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 142, name: "Aerodactyl", isMega: true },
      { pokemonId: 670, name: "Floette" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 981, name: "Farigiraf" },
      { pokemonId: 903, name: "Sneasler" },
    ],
    archetype: "Tailwind",
  },
  {
    id: "t52",
    name: "Floette Gyarados Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 130, name: "Gyarados" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Standard",
  },
  {
    id: "t53",
    name: "Clefable Froslass Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 36, name: "Clefable", isMega: true },
      { pokemonId: 478, name: "Froslass" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Control",
  },
  {
    id: "t54",
    name: "Delphox Goodstuffs",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 655, name: "Delphox", isMega: true },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Hyper Offense",
  },
  {
    id: "t55",
    name: "Gengar Trap Offense",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 94, name: "Gengar", isMega: true },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1018, name: "Archaludon" },
    ],
    archetype: "Control",
  },
  {
    id: "t56",
    name: "Floette No Item Tech",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 530, name: "Excadrill" },
    ],
    archetype: "Standard",
  },
  {
    id: "t57",
    name: "Dragonite Venusaur Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 149, name: "Dragonite", isMega: true },
      { pokemonId: 3, name: "Venusaur" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Sun",
  },
  {
    id: "t58",
    name: "Charizard Y Fairy Feather",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 670, name: "Floette" },
    ],
    archetype: "Sun",
  },
  {
    id: "t59",
    name: "Delphox Floette Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 655, name: "Delphox", isMega: true },
      { pokemonId: 670, name: "Floette" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Balance",
  },
  {
    id: "t60",
    name: "Delphox Floette v2",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 655, name: "Delphox", isMega: true },
      { pokemonId: 670, name: "Floette" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Balance",
  },
  {
    id: "t61",
    name: "Floette Sharp Beak",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Standard",
  },
  {
    id: "t62",
    name: "Froslass Glimmora Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 478, name: "Froslass", isMega: true },
      { pokemonId: 970, name: "Glimmora" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 983, name: "Kingambit" },
    ],
    archetype: "Hyper Offense",
  },
  {
    id: "t63",
    name: "Charizard Y Charcoal",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 670, name: "Floette" },
    ],
    archetype: "Sun",
  },
  {
    id: "t64",
    name: "Floette Metal Coat",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 983, name: "Kingambit" },
    ],
    archetype: "Standard",
  },

  // ═══ Champions Ranked Ladder Teams — Batch 2 (April 12, 2026) ═══

  // ── Sheet Image 4 ──

  {
    id: "t65",
    name: "Froslass Garchomp Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 478, name: "Froslass", isMega: true },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 473, name: "Mamoswine" },
      { pokemonId: 983, name: "Kingambit" },
    ],
    archetype: "Control",
  },
  {
    id: "t66",
    name: "Froslass King's Rock",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 478, name: "Froslass", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Control",
  },
  {
    id: "t67",
    name: "Hawlucha Tyranitar Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 701, name: "Hawlucha", isMega: true },
      { pokemonId: 248, name: "Tyranitar" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Sand",
  },
  {
    id: "t68",
    name: "Delphox Scarf Offense",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 655, name: "Delphox", isMega: true },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Hyper Offense",
  },
  {
    id: "t69",
    name: "Crabominable Meganium Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 740, name: "Crabominable", isMega: true },
      { pokemonId: 154, name: "Meganium" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Trick Room",
  },
  {
    id: "t70",
    name: "Charizard Y Gengar Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 94, name: "Gengar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Sun",
  },
  {
    id: "t71",
    name: "Glimmora Aerodactyl",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 970, name: "Glimmora", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 981, name: "Farigiraf" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
    ],
    archetype: "Hyper Offense",
  },
  {
    id: "t72",
    name: "Aggron Camerupt Starmie Triple Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 306, name: "Aggron", isMega: true },
      { pokemonId: 323, name: "Camerupt" },
      { pokemonId: 121, name: "Starmie" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 981, name: "Farigiraf" },
    ],
    archetype: "Trick Room",
  },
  {
    id: "t73",
    name: "Gyarados Standard",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 130, name: "Gyarados", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Standard",
  },
  {
    id: "t74",
    name: "Aerodactyl Charizard Y Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 142, name: "Aerodactyl", isMega: true },
      { pokemonId: 6, name: "Charizard" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 983, name: "Kingambit" },
    ],
    archetype: "Sun",
  },
  {
    id: "t75",
    name: "Dragonite Froslass Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 149, name: "Dragonite", isMega: true },
      { pokemonId: 478, name: "Froslass" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Balance",
  },
  {
    id: "t76",
    name: "Gardevoir Lucario Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 282, name: "Gardevoir", isMega: true },
      { pokemonId: 448, name: "Lucario" },
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Hyper Offense",
  },
  {
    id: "t77",
    name: "Starmie Fairy Feather",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 121, name: "Starmie", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 670, name: "Floette" },
    ],
    archetype: "Balance",
  },
  {
    id: "t78",
    name: "Dragonite Froslass v2",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 149, name: "Dragonite", isMega: true },
      { pokemonId: 478, name: "Froslass" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 670, name: "Floette" },
    ],
    archetype: "Control",
  },
  {
    id: "t79",
    name: "Floette Aero v2",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Standard",
  },

  // ── Sheet Image 5 ──

  {
    id: "t80",
    name: "Froslass Lum Berry",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 478, name: "Froslass", isMega: true },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 983, name: "Kingambit" },
    ],
    archetype: "Control",
  },
  {
    id: "t81",
    name: "Charizard Y Mental Herb",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 981, name: "Farigiraf" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Sun",
  },
  {
    id: "t82",
    name: "Gengar Scarf Control",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 94, name: "Gengar", isMega: true },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Control",
  },
  {
    id: "t83",
    name: "Floette Bulky Offense",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Standard",
  },
  {
    id: "t84",
    name: "Blastoise Tyranitar Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 9, name: "Blastoise", isMega: true },
      { pokemonId: 248, name: "Tyranitar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 670, name: "Floette" },
    ],
    archetype: "Sand",
  },
  {
    id: "t85",
    name: "Charizard Y Yache Berry",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Sun",
  },
  {
    id: "t86",
    name: "Floette Spell Tag",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Standard",
  },
  {
    id: "t87",
    name: "Dragonite Starmie Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 149, name: "Dragonite", isMega: true },
      { pokemonId: 121, name: "Starmie" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Rain",
  },
  {
    id: "t88",
    name: "Floette Shuca Berry",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1018, name: "Archaludon" },
    ],
    archetype: "Standard",
  },
  {
    id: "t89",
    name: "Drampa Charcoal",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 780, name: "Drampa", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 324, name: "Torkoal" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 981, name: "Farigiraf" },
    ],
    archetype: "Trick Room",
  },
  {
    id: "t90",
    name: "Glimmora Magnet",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 970, name: "Glimmora", isMega: true },
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Hyper Offense",
  },
  {
    id: "t91",
    name: "Charizard Y Roseli Berry",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 670, name: "Floette" },
    ],
    archetype: "Sun",
  },
  {
    id: "t92",
    name: "Gengar Sharp Beak",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 94, name: "Gengar", isMega: true },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 142, name: "Aerodactyl" },
    ],
    archetype: "Control",
  },
  {
    id: "t93",
    name: "Floette Black Belt",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Standard",
  },
  {
    id: "t94",
    name: "Froslass Soft Sand",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 478, name: "Froslass", isMega: true },
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Control",
  },

  // ── Sheet Image 6 ──

  {
    id: "t95",
    name: "Gardevoir Tyranitar Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 282, name: "Gardevoir", isMega: true },
      { pokemonId: 248, name: "Tyranitar" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Sand",
  },
  {
    id: "t96",
    name: "Charizard Y Kingambit v2",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Sun",
  },
  {
    id: "t97",
    name: "Glimmora Mystic Water",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 970, name: "Glimmora", isMega: true },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1018, name: "Archaludon" },
    ],
    archetype: "Rain",
  },
  {
    id: "t98",
    name: "Charizard Y Mystic Water",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 983, name: "Kingambit" },
    ],
    archetype: "Sun",
  },
  {
    id: "t99",
    name: "Alakazam Offense",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 65, name: "Alakazam", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Hyper Offense",
  },
  {
    id: "t100",
    name: "Gengar Mystic Water",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 94, name: "Gengar", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Rain",
  },
  {
    id: "t101",
    name: "Gengar Perish Rain",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 94, name: "Gengar", isMega: true },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1018, name: "Archaludon" },
    ],
    archetype: "Rain",
  },
  {
    id: "t102",
    name: "Froslass King's Rock v2",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 478, name: "Froslass", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Control",
  },
  {
    id: "t103",
    name: "Charizard Y Occa Berry",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Sun",
  },
  {
    id: "t104",
    name: "Charizard Y Leftovers",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Sun",
  },
  {
    id: "t105",
    name: "Kangaskhan Aerodactyl",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 115, name: "Kangaskhan", isMega: true },
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
    ],
    archetype: "Hyper Offense",
  },
  {
    id: "t106",
    name: "Charizard Y Soft Sand",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Sun",
  },
  {
    id: "t107",
    name: "Delphox Metal Coat",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 655, name: "Delphox", isMega: true },
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Balance",
  },
  {
    id: "t108",
    name: "Kangaskhan Charti Berry",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 115, name: "Kangaskhan", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 1018, name: "Archaludon" },
    ],
    archetype: "Standard",
  },
  {
    id: "t109",
    name: "Charizard Y Mental Herb v2",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 981, name: "Farigiraf" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Trick Room",
  },

  // ═══ Champions Ranked Ladder Teams — Batch 3 (April 12, 2026) ═══

  // ── Sheet Image 7 (anonymous ladder teams) ──

  {
    id: "t110",
    name: "Gardevoir Scarf Offense",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 282, name: "Gardevoir", isMega: true },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Hyper Offense",
  },
  {
    id: "t111",
    name: "Tyranitar Leftovers",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 248, name: "Tyranitar", isMega: true },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 1018, name: "Archaludon" },
    ],
    archetype: "Sand",
  },
  {
    id: "t112",
    name: "Delphox Tyranitar Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 655, name: "Delphox", isMega: true },
      { pokemonId: 248, name: "Tyranitar" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Sand",
  },
  {
    id: "t113",
    name: "Chesnaught Gengar Dual Mega v2",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 652, name: "Chesnaught", isMega: true },
      { pokemonId: 94, name: "Gengar" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 670, name: "Floette" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Control",
  },
  {
    id: "t114",
    name: "Charizard Y Tyranitar Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 248, name: "Tyranitar" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 670, name: "Floette" },
      { pokemonId: 903, name: "Sneasler" },
    ],
    archetype: "Sun",
  },
  {
    id: "t115",
    name: "Glimmora Scope Lens",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 970, name: "Glimmora", isMega: true },
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 981, name: "Farigiraf" },
    ],
    archetype: "Hyper Offense",
  },
  {
    id: "t116",
    name: "Froslass Archaludon Core",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 478, name: "Froslass", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Control",
  },
  {
    id: "t117",
    name: "Golurk Fairy Feather",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 623, name: "Golurk", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 981, name: "Farigiraf" },
      { pokemonId: 670, name: "Floette" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Trick Room",
  },
  {
    id: "t118",
    name: "Gardevoir Mystic Water",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 282, name: "Gardevoir", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Balance",
  },
  {
    id: "t119",
    name: "Gardevoir Chople Berry",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 282, name: "Gardevoir", isMega: true },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Balance",
  },
  {
    id: "t120",
    name: "Dragonite Starmie v2",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 149, name: "Dragonite", isMega: true },
      { pokemonId: 121, name: "Starmie" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Rain",
  },
  {
    id: "t121",
    name: "Gengar Dragon Fang",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 94, name: "Gengar", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 1018, name: "Archaludon" },
    ],
    archetype: "Control",
  },
  {
    id: "t122",
    name: "Floette Gyarados v2",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 130, name: "Gyarados" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 1018, name: "Archaludon" },
    ],
    archetype: "Standard",
  },
  {
    id: "t123",
    name: "Charizard Y Gengar v2",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 94, name: "Gengar" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 983, name: "Kingambit" },
    ],
    archetype: "Sun",
  },

  // ── Sheet Image 8 (anonymous ladder teams) ──

  {
    id: "t124",
    name: "Gengar Shuca Berry",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 94, name: "Gengar", isMega: true },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1018, name: "Archaludon" },
    ],
    archetype: "Control",
  },
  {
    id: "t125",
    name: "Aerodactyl Black Belt",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 142, name: "Aerodactyl", isMega: true },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Hyper Offense",
  },
  {
    id: "t126",
    name: "Glimmora Mental Herb",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 970, name: "Glimmora", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 981, name: "Farigiraf" },
    ],
    archetype: "Hyper Offense",
  },
  {
    id: "t127",
    name: "Charizard Y Black Glasses",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Sun",
  },
  {
    id: "t128",
    name: "Charizard Y Farigiraf",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 981, name: "Farigiraf" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Trick Room",
  },
  {
    id: "t129",
    name: "Tyranitar Quick Claw",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 248, name: "Tyranitar", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 1018, name: "Archaludon" },
    ],
    archetype: "Sand",
  },
  {
    id: "t130",
    name: "Floette Tyranitar v2",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 248, name: "Tyranitar" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Sand",
  },
  {
    id: "t131",
    name: "Charizard Y Gardevoir Dual Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 282, name: "Gardevoir" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Sun",
  },
  {
    id: "t132",
    name: "Floette Gyarados v3",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 130, name: "Gyarados" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 983, name: "Kingambit" },
    ],
    archetype: "Standard",
  },
  {
    id: "t133",
    name: "Gengar Froslass Control v2",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 94, name: "Gengar", isMega: true },
      { pokemonId: 478, name: "Froslass" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Control",
  },
  {
    id: "t134",
    name: "Charizard Y Gardevoir v2",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 282, name: "Gardevoir" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Sun",
  },
  {
    id: "t135",
    name: "Floette Kingambit Core",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Standard",
  },
  {
    id: "t136",
    name: "Drampa Torkoal TR",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 780, name: "Drampa", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 324, name: "Torkoal" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 981, name: "Farigiraf" },
    ],
    archetype: "Trick Room",
  },
  {
    id: "t137",
    name: "Glimmora Aerodactyl v2",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 970, name: "Glimmora", isMega: true },
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Hyper Offense",
  },
  {
    id: "t138",
    name: "Charizard Y Garchomp v2",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 983, name: "Kingambit" },
    ],
    archetype: "Sun",
  },
  {
    id: "t139",
    name: "Gengar Garchomp Core",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 94, name: "Gengar", isMega: true },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Control",
  },
  {
    id: "t140",
    name: "Floette Roseli Berry",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Standard",
  },
  {
    id: "t141",
    name: "Froslass Aerodactyl v2",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 478, name: "Froslass", isMega: true },
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Control",
  },
  {
    id: "t142",
    name: "Clefable Froslass Lucario Triple Mega",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 36, name: "Clefable", isMega: true },
      { pokemonId: 478, name: "Froslass" },
      { pokemonId: 448, name: "Lucario" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Control",
  },
  {
    id: "t143",
    name: "Charizard X Offense",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 0 },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Hyper Offense",
  },
  {
    id: "t144",
    name: "Charizard Y Lum Berry",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
    ],
    archetype: "Sun",
  },
  {
    id: "t145",
    name: "Gengar Starmie v2",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 94, name: "Gengar", isMega: true },
      { pokemonId: 121, name: "Starmie" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 902, name: "Basculegion-M" },
    ],
    archetype: "Control",
  },
  {
    id: "t146",
    name: "Blastoise Scarf",
    player: "Ranked Ladder",
    placement: "Top Cut",
    event: "Champions Ranked Ladder (April 2026)",
    pokemon: [
      { pokemonId: 9, name: "Blastoise", isMega: true },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Rain",
  },

  // ═══ Champions Tournament Teams — With Player Names (April 2026) ═══
  // Source: Limitless VGC, VGCPastes, Ranked Tournaments

  {
    id: "t147",
    name: "Chesnaught Feraligatr Core",
    player: "Castorbrown",
    placement: "Top Cut",
    event: "Champions Tournament (April 2026)",
    pokemon: [
      { pokemonId: 652, name: "Chesnaught", isMega: true },
      { pokemonId: 160, name: "Feraligatr" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Bulky Offense",
  },
  {
    id: "t148",
    name: "Greninja Meganium Dual Mega",
    player: "AxolotlMan",
    placement: "Top Cut",
    event: "Champions Tournament (April 2026)",
    pokemon: [
      { pokemonId: 658, name: "Greninja", isMega: true },
      { pokemonId: 154, name: "Meganium" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 727, name: "Incineroar" },
    ],
    archetype: "Rain",
  },
  {
    id: "t149",
    name: "Hawlucha HO v2",
    player: "Shoma Honami",
    placement: "Top Cut",
    event: "Champions Tournament (April 2026)",
    pokemon: [
      { pokemonId: 701, name: "Hawlucha", isMega: true },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 983, name: "Kingambit" },
    ],
    archetype: "Hyper Offense",
  },
  {
    id: "t150",
    name: "Dragonite Rain v2",
    player: "Ioannis Baziotis",
    placement: "Top Cut",
    event: "Champions Tournament (April 2026)",
    pokemon: [
      { pokemonId: 149, name: "Dragonite", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Balance",
  },
  {
    id: "t151",
    name: "Charizard Y Gengar Dual",
    player: "kurbito",
    placement: "Top Cut",
    event: "Champions Tournament (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 94, name: "Gengar" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 1018, name: "Archaludon" },
    ],
    archetype: "Sun",
  },
  {
    id: "t152",
    name: "Gengar Perish Trap",
    player: "Alex Gómez",
    placement: "Top Cut",
    event: "Champions Tournament (April 2026)",
    pokemon: [
      { pokemonId: 94, name: "Gengar", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Control",
  },
  {
    id: "t153",
    name: "Charizard Y Yache Berry",
    player: "Ko Tsukide",
    placement: "Top Cut",
    event: "Champions Tournament (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Sun",
  },
  {
    id: "t154",
    name: "Floette Balance",
    player: "Maxime Solemn",
    placement: "Top Cut",
    event: "Champions Tournament (April 2026)",
    pokemon: [
      { pokemonId: 10061, name: "Eternal Floette", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 981, name: "Farigiraf" },
      { pokemonId: 1018, name: "Archaludon" },
    ],
    archetype: "Standard",
  },
  {
    id: "t155",
    name: "Froslass Dark Core",
    player: "white_shade25",
    placement: "Top Cut",
    event: "Champions Tournament (April 2026)",
    pokemon: [
      { pokemonId: 478, name: "Froslass", isMega: true },
      { pokemonId: 142, name: "Aerodactyl" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Control",
  },
  {
    id: "t156",
    name: "Charizard Y Sand",
    player: "Chyr Wei",
    placement: "Top Cut",
    event: "Champions Tournament (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 530, name: "Excadrill" },
    ],
    archetype: "Sun",
  },
  {
    id: "t157",
    name: "Aerodactyl Floette v2",
    player: "Ze Banded",
    placement: "Top Cut",
    event: "Champions Tournament (April 2026)",
    pokemon: [
      { pokemonId: 142, name: "Aerodactyl", isMega: true },
      { pokemonId: 670, name: "Floette" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
    ],
    archetype: "Tailwind",
  },
  {
    id: "t158",
    name: "Charizard Y Gengar v3",
    player: "Apex__Dragon",
    placement: "Top Cut",
    event: "Champions Tournament (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 94, name: "Gengar" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 981, name: "Farigiraf" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Sun",
  },
  {
    id: "t159",
    name: "Charizard Y Dragon Fang",
    player: "Sarapoke0914",
    placement: "Top Cut",
    event: "Champions Tournament (April 2026)",
    pokemon: [
      { pokemonId: 6, name: "Charizard", isMega: true, megaFormIndex: 1 },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
      { pokemonId: 1018, name: "Archaludon" },
    ],
    archetype: "Sun",
  },
  {
    id: "t160",
    name: "Froslass Fairy Feather",
    player: "Will Inabinet",
    placement: "Top Cut",
    event: "Champions Tournament (April 2026)",
    pokemon: [
      { pokemonId: 478, name: "Froslass", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 1018, name: "Archaludon" },
      { pokemonId: 983, name: "Kingambit" },
      { pokemonId: 670, name: "Floette" },
    ],
    archetype: "Control",
  },
  {
    id: "t161",
    name: "Gengar Rain Trap",
    player: "Sarapoke0914",
    placement: "Top Cut",
    event: "Champions Tournament (April 2026)",
    pokemon: [
      { pokemonId: 94, name: "Gengar", isMega: true },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 279, name: "Pelipper" },
      { pokemonId: 981, name: "Farigiraf" },
      { pokemonId: 1018, name: "Archaludon" },
    ],
    archetype: "Rain",
  },
  {
    id: "t162",
    name: "Meganium Balance",
    player: "Nate Innocenti",
    placement: "Top Cut",
    event: "Champions Tournament (April 2026)",
    pokemon: [
      { pokemonId: 154, name: "Meganium", isMega: true },
      { pokemonId: 445, name: "Garchomp" },
      { pokemonId: 902, name: "Basculegion-M" },
      { pokemonId: 727, name: "Incineroar" },
      { pokemonId: 903, name: "Sneasler" },
      { pokemonId: 1013, name: "Sinistcha" },
    ],
    archetype: "Balance",
  },
];
